### ISSUE TITLE
Error: .vimrc

### ISSUE THREAD

**Issue by tyrollins** [appacademy/dotfiles#13]
Just setup my machine with your dotfiles, and received the below error when starting vim. 

I then installed vundle separately and all was good in the world. Curious as to the reason not to include vundle in the installation, or if it was an error on my part. 

```
Error detected while processing /Users/username/.vimrc:
line    6:
E117: Unknown function: vundle#begin
line   11:
E492: Not an editor command: Plugin 'gmarik/Vundle.vim'
line   13:
E492: Not an editor command: Plugin 'flazz/vim-colorschemes'
line   14:
E492: Not an editor command: Plugin 'scrooloose/nerdtree'
line   15:
E492: Not an editor command: Plugin 'tomasr/molokai'
line   18:
E117: Unknown function: vundle#end
line   23:
E185: Cannot find color scheme molokai
```

Thank you for open sourcing these dotfiles, very helpful!

**Comment by wolverdude** [comment]
I've refactored the dotfiles to include only minimal and basic configuration so that it will be easier for students to understand and build off of. This means the `.vimrc` has been removed since we don't teach Vim.
