### ISSUE TITLE
Add Linux configuration

### ISSUE THREAD

**Issue by wolverdude** [appacademy/dotfiles#18]
We may need to add multiple scripts for Debian, Red Hat, Arch, etc.

**Comment by rglassett** [comment]
Is it within the scope of this repo to play nicely with the various distros/package managers? Aside from differences in the commands themselves, package managers often disagree with each other about what versions are 'stable', which means getting any sort of reproducibility across distros will be a Sisyphean task.

**Comment by wolverdude** [comment]
This is a fair point, but 90% of what this repo does is `rbenv`, `nvm`, `atom` and `bash`, all of which are standard across *NIX systems, at least in their basic form. I think we could factor out a *NIX core and include a list of system requirements in the readme that need to set up manually before they run the script.

**Comment by wolverdude** [comment]
That said, this is still more of a nice-to-have than a necessity.

**Comment by mfeniseycopes** [comment]
I wrote [this](https://github.com/mfeniseycopes/linux-dev-setup) up yesterday and would love to merge it into the dotfiles repo. It is strictly for Ubuntu Linux and has instructions for installation (dual boot or otherwise) and includes and script to setup the dev environment.

Let me know what you think.

**Comment by wolverdude** [comment]
Nice! We'll have to look at it and try it out over here. Have you run the script on any machines in NY?

**Comment by mfeniseycopes** [comment]
I test ran it on my linux machine yesterday, right after a fresh install of Ubuntu 16.04. It ran smoothly with no hiccups.

**Comment by wolverdude** [comment]
Okay. I won't have time to look into this myself, but I'll delegate it to one of the Hackers in Residence. We might not get to it for a couple weeks, but it should be ready before the next NY cohort starts.

**Comment by mfeniseycopes** [comment]
Sure, no problem at all.

**Comment by niko79542** [comment]
Script worked great for me.

`gem install rails` defaults to the latest version (5.0), which was giving us problems when going through the curriculum.  With rails 5, I had to specify version # whenever I made an app for class (e.g. rails _4.2.7.1_ new myapp)

Maybe change to  `gem install rails -v 4.2.7.1`?

**Comment by wolverdude** [comment]
That shouldn't happen. Rails should be installed from the Gemfile in this repository, which specifies the version.

Please go through the linux install script and make sure it properly parallels the mac one, both in content and style. I'll create a branch for you to do this on.

**Comment by wolverdude** [comment]
Fixed by #23.
