### ISSUE TITLE
Update machine-setup

### ISSUE THREAD

**Issue by rglassett** [appacademy/dotfiles#2]
We should update the machine-setup instructions to reflect changes we've made (Atom over Textmate, etc).

I'd also like it if we took Terminal off of the dock entirely, and made sure that new Terminal tabs opened on the previous working directory.

Finally (and shoot me down if this would be just too tyrannical), I am tempted to put restrictions on the student account so they can't move/resize the dock, install stupid apps/color schemes, etc. Not a lot of students do this, but I do value having a consistent environment.

**Comment by davidrunger** [comment]
Are you saying that you want to remove Terminal from the dock so that students will prefer iTerm?

**Comment by rglassett** [comment]
Indeed!

**Comment by rglassett** [comment]
Also we should add the [W3 Schools Hider](https://chrome.google.com/webstore/detail/w3schools-hider/igiahejkpbnbnekdaefddmdceocmjpll?hl=en-US) extension to Chrome.

**Comment by rglassett** [comment]
I think most of this has been added to the README, so I'm closing this for now.
