### ISSUE TITLE
Don't use edge versions of Rails

### ISSUE THREAD

**Issue by davidrunger** [appacademy/dotfiles#4]
We ran into some Rails bugs this cohort (something about frozen attributes, see https://github.com/rails/rails/issues/17960) because the Mac Minis have Rails 4.2.0rc2 installed. To avoid this and similar problems in the future, we should probably specify a Rails version in https://github.com/appacademy/dotfiles/blob/master/setup/Gemfile, right?

**Comment by rglassett** [comment]
I've been addressing this as I set up the new stations. So far I think all the stations in the Sunset pod are good. I'll post again when they're all fixed, but we should leave this open until we make a new image.

**Comment by davidrunger** [comment]
I updated the Gemfile with 5f49336 and also went around to the SF pairing stations this morning and made sure that each is running Rails 4.2.0 (not Rails 4.2.0rc1 or not Rails 4.2.0rc1, as most of them were before I came around with my `gem update rails`.)
