### ISSUE TITLE
Assign desk numbers

### ISSUE THREAD

**Issue by rglassett** [appacademy/dotfiles#7]
So people can find their stations and partners easily in the mornings. May require changes to @jonathanlemuel's [chrome extension][chrome-extension] repo. The extension seems to care only about desk number and not pod number, so we wind up with multiple pairs per desk in SF.

[chrome-extension]: https://github.com/jonathanlemuel/app-academy-chrome-tab

**Comment by w1zeman1p** [comment]
This is done, now we need to assign pods in the chrome extension
