### ISSUE TITLE
Write install script

### ISSUE THREAD

**Issue by rglassett** [appacademy/dotfiles#9]
Would be nice to have something similar to https://github.com/thoughtbot/laptop so we don't have to do all the brew/rbenv installs by hand when we image. It'd be nice to have a reliable setup procedure for students, as well.

**Comment by whastings** [comment]
I've done something similar with my dotfiles. I have:

* A [linux_setup](https://github.com/whastings/dot-files/blob/master/bin/linux_setup) script for when I work on Ubuntu. Gotta make a Mac one at some point.
* An [install](https://github.com/whastings/dot-files/blob/master/bin/install) script for symlinking dotfiles, installing nvm and rbenv, and setting up vim.

**Comment by rglassett** [comment]
:+1:

**Comment by wolverdude** [comment]
Done, and redone.

**Comment by wolverdude** [comment]
Currently only support Mac though.
